all:
  vars:
    ansible_connection: aws_ssm
    ansible_user: ubuntu
    ansible_aws_ssm_region: us-east-1

  children:

    frontend:
      hosts:
        frontend:
          ansible_host: "{{ lookup('env', 'FRONTEND_INSTANCE_ID') }}"

    backend:
      hosts:
        backend:
          ansible_host: "{{ lookup('env', 'BACKEND_INSTANCE_ID') }}"